server:
  port: 8081
app:
  url: http://localhost:8081
  dummy-email: abdullah2224@gmail.com
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
spring:
  application:
    name: void-user
  datasource:
    url: ${DB_URL}
    default_schema: usr
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true